const LANGS = ["pt-br", "en", "es"];
const ROOT = new URL("../kb/", import.meta.url).pathname;
const OUT_TS = new URL("../supabase/functions/_shared/kb-cache.ts", import.meta.url).pathname;
const OUT_JSON_CHAT = new URL("../supabase/functions/chat/kb-cache.json", import.meta.url).pathname;
const OUT_JSON_SUMMARIZE = new URL("../supabase/functions/summarize-daily/kb-cache.json", import.meta.url).pathname;

const out: Record<string, string> = {};

for (const lang of LANGS) {
  const dir = `${ROOT}${lang}`;
  try {
    const entries = [];
    for await (const e of Deno.readDir(dir)) {
      if (e.isFile && e.name.endsWith(".md")) entries.push(e.name);
    }
    entries.sort((a, b) => a.localeCompare(b));
    const parts: string[] = [];
    for (const name of entries) {
      const content = await Deno.readTextFile(`${dir}/${name}`);
      parts.push(`## [${name}]\n${content}`);
    }
    out[lang] = parts.join("\n\n");
  } catch {
    out[lang] = "";
  }
}

// Generate TypeScript module so the cache is bundled with edge functions (CLI deploy skips .json files)
const tsContent = `// AUTO-GENERATED by scripts/build-kb-cache.ts. Do not edit by hand.
// Run: deno run --allow-read --allow-write scripts/build-kb-cache.ts

export const KB_CACHE: Record<"pt-br" | "en" | "es", string> = ${JSON.stringify(out, null, 2)};
`;
await Deno.writeTextFile(OUT_TS, tsContent);

// Keep JSON outputs for local dev / tests parity
await Deno.writeTextFile(OUT_JSON_CHAT, JSON.stringify(out, null, 2));
await Deno.writeTextFile(OUT_JSON_SUMMARIZE, JSON.stringify(out, null, 2));

console.log(`Built KB cache: ${Object.entries(out).map(([k, v]) => `${k}=${v.length}ch`).join(", ")}`);
