// Reads tom-de-voz-do-assistente.md and perguntas-frequentes-e-erros.md from
// the canonical KB folder in Drive, and emits supabase/functions/_shared/fixed-context.ts
// as a TS module. The two files are ALWAYS injected as fixed context (every chat turn).

const ROOT =
  "/Users/rodrigorosar/Library/CloudStorage/GoogleDrive-rodrigo@rodrigorosar.com.br/Meu Drive/METRIK I Cérebro/40 Metrik Instituto/41 Cursos/1 Click Render/_publico";

const OUT = new URL("../supabase/functions/_shared/fixed-context.ts", import.meta.url).pathname;

const tom = await Deno.readTextFile(`${ROOT}/tom-de-voz-do-assistente.md`);
const faq = await Deno.readTextFile(`${ROOT}/perguntas-frequentes-e-erros.md`);

function tsEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const out = `// AUTO-GENERATED by scripts/build-fixed-context.ts — do not edit by hand.
// Run: deno run --allow-read --allow-write scripts/build-fixed-context.ts

export const TOM_DE_VOZ = \`${tsEscape(tom)}\`;

export const FAQ_E_ERROS = \`${tsEscape(faq)}\`;
`;

await Deno.writeTextFile(OUT, out);
console.log(`Built fixed-context.ts: tom=${tom.length}ch, faq=${faq.length}ch`);
